#!/bin/sh
set -e

chown -R www-data:www-data /var/www/html/storage

php artisan storage:link

php artisan config:cache
php artisan route:cache
php artisan view:cache

php artisan migrate

exec docker-php-entrypoint "$@"
